import { IResUserProps } from "./src/types/users";

export const users: IResUserProps[] = [
  {
    name: "김 메라",
    contact: {
      phone: "010-0000-0000",
      email: "madeline@gmail.com",
    },
    birthdate: "1980-08-08",
    gender: "여성",
    location: "남양주 다산점",
    account: {
      id: "madeline@gmail.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "VIP",
      registeredAt: "2020-12-25",
      lastReRegisteredAt: "2025-02-25",
      expirationDate: "2025-03-25",
    },
    stats: {
      height: 170,
      currentWeight: 75,
      goalWeight: 60,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "무직백수",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "박 민수",
    contact: {
      phone: "010-1234-5678",
      email: "minsu@naver.com",
    },
    birthdate: "1985-03-15",
    gender: "남성",
    location: "남양주 다산점",
    account: {
      id: "minsu@naver.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "신규",
      registeredAt: "2023-05-10",
      lastReRegisteredAt: "2024-05-10",
      expirationDate: "2025-05-10",
    },
    stats: {
      height: 178,
      currentWeight: 82,
      goalWeight: 75,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "이 지영",
    contact: {
      phone: "010-9876-5432",
      email: "jiyoung@gmail.com",
    },
    birthdate: "1992-11-23",
    gender: "여성",
    location: "남양주 다산점",
    account: {
      id: "jiyoung@gmail.com",
      role: "admin",
    },
    membership: {
      type: "체험회원",
      level: "신규",
      registeredAt: "2024-06-15",
      lastReRegisteredAt: "2024-06-15",
      expirationDate: "2024-07-15",
    },
    stats: {
      height: 163,
      currentWeight: 58,
      goalWeight: 52,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "최 준호",
    contact: {
      phone: "010-2345-6789",
      email: "junho@daum.net",
    },
    birthdate: "1978-05-20",
    gender: "남성",
    location: "남양주 다산점",
    account: {
      id: "junho@daum.net",
      role: "admin",
    },
    membership: {
      type: "종료",
      level: "신규",
      registeredAt: "2022-01-15",
      lastReRegisteredAt: "2023-01-15",
      expirationDate: "2024-01-15",
    },
    stats: {
      height: 175,
      currentWeight: 80,
      goalWeight: 72,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "정 수연",
    contact: {
      phone: "010-3456-7890",
      email: "suyeon@gmail.com",
    },
    birthdate: "1995-09-12",
    gender: "여성",
    location: "남양주 다산점",
    account: {
      id: "suyeon@gmail.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "신규",
      registeredAt: "2021-08-05",
      lastReRegisteredAt: "2024-08-05",
      expirationDate: "2025-08-05",
    },
    stats: {
      height: 168,
      currentWeight: 62,
      goalWeight: 55,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "강 동욱",
    contact: {
      phone: "010-4567-8901",
      email: "dongwook@naver.com",
    },
    birthdate: "1983-07-28",
    gender: "남성",
    location: "남양주 다산점",
    account: {
      id: "dongwook@naver.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "신규",
      registeredAt: "2023-11-20",
      lastReRegisteredAt: "2024-11-20",
      expirationDate: "2025-11-20",
    },
    stats: {
      height: 182,
      currentWeight: 88,
      goalWeight: 80,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "윤 미라",
    contact: {
      phone: "010-5678-9012",
      email: "mira@gmail.com",
    },
    birthdate: "1990-02-14",
    gender: "여성",
    location: "남양주 다산점",
    account: {
      id: "mira@gmail.com",
      role: "admin",
    },
    membership: {
      type: "체험회원",
      level: "신규",
      registeredAt: "2024-06-01",
      lastReRegisteredAt: "2024-06-01",
      expirationDate: "2024-07-01",
    },
    stats: {
      height: 165,
      currentWeight: 60,
      goalWeight: 53,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "송 현우",
    contact: {
      phone: "010-6789-0123",
      email: "hyunwoo@kakao.com",
    },
    birthdate: "1988-12-05",
    gender: "남성",
    location: "남양주 다산점",
    account: {
      id: "hyunwoo@kakao.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "신규",
      registeredAt: "2022-09-15",
      lastReRegisteredAt: "2024-09-15",
      expirationDate: "2025-09-15",
    },
    stats: {
      height: 179,
      currentWeight: 84,
      goalWeight: 76,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "임 수진",
    contact: {
      phone: "010-7890-1234",
      email: "sujin@naver.com",
    },
    birthdate: "1993-04-18",
    gender: "여성",
    location: "남양주 다산점",
    account: {
      id: "sujin@naver.com",
      role: "admin",
    },
    membership: {
      type: "종료",
      level: "신규",
      registeredAt: "2022-05-10",
      lastReRegisteredAt: "2023-05-10",
      expirationDate: "2024-05-10",
    },
    stats: {
      height: 162,
      currentWeight: 57,
      goalWeight: 50,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "한 지훈",
    contact: {
      phone: "010-8901-2345",
      email: "jihoon@gmail.com",
    },
    birthdate: "1982-10-30",
    gender: "남성",
    location: "남양주 다산점",
    account: {
      id: "jihoon@gmail.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "신규",
      registeredAt: "2020-03-15",
      lastReRegisteredAt: "2024-03-15",
      expirationDate: "2025-03-15",
    },
    stats: {
      height: 176,
      currentWeight: 79,
      goalWeight: 72,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "오 은지",
    contact: {
      phone: "010-9012-3456",
      email: "eunji@daum.net",
    },
    birthdate: "1997-06-25",
    gender: "여성",
    location: "양주 옥정점",
    account: {
      id: "eunji@daum.net",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "신규",
      registeredAt: "2024-05-20",
      lastReRegisteredAt: "2024-05-20",
      expirationDate: "2025-05-20",
    },
    stats: {
      height: 167,
      currentWeight: 63,
      goalWeight: 55,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "신 태영",
    contact: {
      phone: "010-0123-4567",
      email: "taeyoung@naver.com",
    },
    birthdate: "1975-01-12",
    gender: "남성",
    location: "양주 옥정점",
    account: {
      id: "taeyoung@naver.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "신규",
      registeredAt: "2023-02-10",
      lastReRegisteredAt: "2024-02-10",
      expirationDate: "2025-02-10",
    },
    stats: {
      height: 177,
      currentWeight: 83,
      goalWeight: 75,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "조 유진",
    contact: {
      phone: "010-1234-5678",
      email: "yujin@gmail.com",
    },
    birthdate: "1994-08-03",
    gender: "여성",
    location: "양주 옥정점",
    account: {
      id: "yujin@gmail.com",
      role: "admin",
    },
    membership: {
      type: "체험회원",
      level: "신규",
      registeredAt: "2024-06-10",
      lastReRegisteredAt: "2024-06-10",
      expirationDate: "2024-07-10",
    },
    stats: {
      height: 164,
      currentWeight: 59,
      goalWeight: 52,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "권 성민",
    contact: {
      phone: "010-2345-6789",
      email: "seongmin@kakao.com",
    },
    birthdate: "1986-09-17",
    gender: "남성",
    location: "양주 옥정점",
    account: {
      id: "seongmin@kakao.com",
      role: "admin",
    },
    membership: {
      type: "종료",
      level: "신규",
      registeredAt: "2021-10-05",
      lastReRegisteredAt: "2023-10-05",
      expirationDate: "2024-04-05",
    },
    stats: {
      height: 180,
      currentWeight: 85,
      goalWeight: 78,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "황 지은",
    contact: {
      phone: "010-3456-7890",
      email: "jieun@naver.com",
    },
    birthdate: "1991-12-28",
    gender: "여성",
    location: "양주 옥정점",
    account: {
      id: "jieun@naver.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "재등록",
      registeredAt: "2022-11-15",
      lastReRegisteredAt: "2023-11-15",
      expirationDate: "2024-11-15",
    },
    stats: {
      height: 166,
      currentWeight: 61,
      goalWeight: 54,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "안 현석",
    contact: {
      phone: "010-4567-8901",
      email: "hyunseok@gmail.com",
    },
    birthdate: "1984-05-09",
    gender: "남성",
    location: "양주 옥정점",
    account: {
      id: "hyunseok@gmail.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "재등록",
      registeredAt: "2021-04-20",
      lastReRegisteredAt: "2024-04-20",
      expirationDate: "2025-04-20",
    },
    stats: {
      height: 181,
      currentWeight: 87,
      goalWeight: 80,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "이 하은",
    contact: {
      phone: "010-5678-9012",
      email: "haeun@daum.net",
    },
    birthdate: "1996-02-14",
    gender: "여성",
    location: "양주 옥정점",
    account: {
      id: "haeun@daum.net",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "재등록",
      registeredAt: "2024-04-05",
      lastReRegisteredAt: "2024-04-05",
      expirationDate: "2025-04-05",
    },
    stats: {
      height: 169,
      currentWeight: 64,
      goalWeight: 56,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "김 도현",
    contact: {
      phone: "010-6789-0123",
      email: "dohyun@naver.com",
    },
    birthdate: "1989-07-22",
    gender: "남성",
    location: "양주 옥정점",
    account: {
      id: "dohyun@naver.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "재등록",
      registeredAt: "2023-08-10",
      lastReRegisteredAt: "2024-08-10",
      expirationDate: "2025-08-10",
    },
    stats: {
      height: 178,
      currentWeight: 81,
      goalWeight: 74,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "박 소연",
    contact: {
      phone: "010-7890-1234",
      email: "soyeon@gmail.com",
    },
    birthdate: "1993-11-05",
    gender: "여성",
    location: "양주 옥정점",
    account: {
      id: "soyeon@gmail.com",
      role: "admin",
    },
    membership: {
      type: "체험회원",
      level: "재등록",
      registeredAt: "2024-06-20",
      lastReRegisteredAt: "2024-06-20",
      expirationDate: "2024-07-20",
    },
    stats: {
      height: 165,
      currentWeight: 60,
      goalWeight: 53,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "최 재민",
    contact: {
      phone: "010-8901-2345",
      email: "jaemin@kakao.com",
    },
    birthdate: "1981-03-18",
    gender: "남성",
    location: "양주 옥정점",
    account: {
      id: "jaemin@kakao.com",
      role: "admin",
    },
    membership: {
      type: "종료",
      level: "재등록",
      registeredAt: "2022-02-25",
      lastReRegisteredAt: "2023-02-25",
      expirationDate: "2024-02-25",
    },
    stats: {
      height: 176,
      currentWeight: 82,
      goalWeight: 75,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "정 예진",
    contact: {
      phone: "010-9012-3456",
      email: "yejin@naver.com",
    },
    birthdate: "1992-04-15",
    gender: "여성",
    location: "의정부 가능점",
    account: {
      id: "yejin@naver.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "재등록",
      registeredAt: "2023-03-10",
      lastReRegisteredAt: "2024-03-10",
      expirationDate: "2025-03-10",
    },
    stats: {
      height: 163,
      currentWeight: 58,
      goalWeight: 52,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "김 준영",
    contact: {
      phone: "010-2345-6789",
      email: "junyoung@gmail.com",
    },
    birthdate: "1987-09-23",
    gender: "남성",
    location: "의정부 가능점",
    account: {
      id: "junyoung@gmail.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "재등록",
      registeredAt: "2022-01-15",
      lastReRegisteredAt: "2024-01-15",
      expirationDate: "2025-01-15",
    },
    stats: {
      height: 179,
      currentWeight: 83,
      goalWeight: 76,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "이 민지",
    contact: {
      phone: "010-3456-7890",
      email: "minji@daum.net",
    },
    birthdate: "1994-11-12",
    gender: "여성",
    location: "의정부 가능점",
    account: {
      id: "minji@daum.net",
      role: "admin",
    },
    membership: {
      type: "체험회원",
      level: "재등록",
      registeredAt: "2024-06-25",
      lastReRegisteredAt: "2024-06-25",
      expirationDate: "2024-07-25",
    },
    stats: {
      height: 166,
      currentWeight: 61,
      goalWeight: 54,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "박 현우",
    contact: {
      phone: "010-4567-8901",
      email: "hyunwoo@naver.com",
    },
    birthdate: "1983-02-28",
    gender: "남성",
    location: "의정부 가능점",
    account: {
      id: "hyunwoo@naver.com",
      role: "admin",
    },
    membership: {
      type: "종료",
      level: "재등록",
      registeredAt: "2021-12-10",
      lastReRegisteredAt: "2022-12-10",
      expirationDate: "2023-12-10",
    },
    stats: {
      height: 177,
      currentWeight: 84,
      goalWeight: 76,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "최 지원",
    contact: {
      phone: "010-5678-9012",
      email: "jiwon@gmail.com",
    },
    birthdate: "1996-07-19",
    gender: "여성",
    location: "의정부 가능점",
    account: {
      id: "jiwon@gmail.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "재등록",
      registeredAt: "2024-02-15",
      lastReRegisteredAt: "2024-02-15",
      expirationDate: "2025-02-15",
    },
    stats: {
      height: 168,
      currentWeight: 63,
      goalWeight: 55,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "강 성훈",
    contact: {
      phone: "010-6789-0123",
      email: "sunghoon@kakao.com",
    },
    birthdate: "1979-10-05",
    gender: "남성",
    location: "의정부 가능점",
    account: {
      id: "sunghoon@kakao.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "재등록",
      registeredAt: "2023-09-20",
      lastReRegisteredAt: "2024-09-20",
      expirationDate: "2025-09-20",
    },
    stats: {
      height: 175,
      currentWeight: 80,
      goalWeight: 73,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "윤 소희",
    contact: {
      phone: "010-7890-1234",
      email: "sohee@naver.com",
    },
    birthdate: "1991-05-27",
    gender: "여성",
    location: "의정부 가능점",
    account: {
      id: "sohee@naver.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "재등록",
      registeredAt: "2020-08-15",
      lastReRegisteredAt: "2024-08-15",
      expirationDate: "2025-08-15",
    },
    stats: {
      height: 164,
      currentWeight: 59,
      goalWeight: 52,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "임 준서",
    contact: {
      phone: "010-8901-2345",
      email: "junseo@gmail.com",
    },
    birthdate: "1988-12-14",
    gender: "남성",
    location: "의정부 가능점",
    account: {
      id: "junseo@gmail.com",
      role: "admin",
    },
    membership: {
      type: "체험회원",
      level: "VIP",
      registeredAt: "2024-06-05",
      lastReRegisteredAt: "2024-06-05",
      expirationDate: "2024-07-05",
    },
    stats: {
      height: 181,
      currentWeight: 86,
      goalWeight: 78,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "한 유나",
    contact: {
      phone: "010-9012-3456",
      email: "yuna@daum.net",
    },
    birthdate: "1995-01-30",
    gender: "여성",
    location: "의정부 가능점",
    account: {
      id: "yuna@daum.net",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "VIP",
      registeredAt: "2023-04-10",
      lastReRegisteredAt: "2024-04-10",
      expirationDate: "2025-04-10",
    },
    stats: {
      height: 167,
      currentWeight: 62,
      goalWeight: 55,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "송 민재",
    contact: {
      phone: "010-0123-4567",
      email: "minjae@naver.com",
    },
    birthdate: "1984-06-08",
    gender: "남성",
    location: "의정부 가능점",
    account: {
      id: "minjae@naver.com",
      role: "admin",
    },
    membership: {
      type: "종료",
      level: "VIP",
      registeredAt: "2022-07-15",
      lastReRegisteredAt: "2023-07-15",
      expirationDate: "2024-07-15",
    },
    stats: {
      height: 180,
      currentWeight: 85,
      goalWeight: 77,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "조 은서",
    contact: {
      phone: "010-1234-5678",
      email: "eunseo@gmail.com",
    },
    birthdate: "1997-09-03",
    gender: "여성",
    location: "파주 운정점",
    account: {
      id: "eunseo@gmail.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "VIP",
      registeredAt: "2024-01-20",
      lastReRegisteredAt: "2024-01-20",
      expirationDate: "2025-01-20",
    },
    stats: {
      height: 165,
      currentWeight: 60,
      goalWeight: 53,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "권 태현",
    contact: {
      phone: "010-2345-6789",
      email: "taehyun@kakao.com",
    },
    birthdate: "1982-04-17",
    gender: "남성",
    location: "파주 운정점",
    account: {
      id: "taehyun@kakao.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "VIP",
      registeredAt: "2021-05-25",
      lastReRegisteredAt: "2024-05-25",
      expirationDate: "2025-05-25",
    },
    stats: {
      height: 176,
      currentWeight: 81,
      goalWeight: 74,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "황 서연",
    contact: {
      phone: "010-3456-7890",
      email: "seoyeon@naver.com",
    },
    birthdate: "1993-08-22",
    gender: "여성",
    location: "파주 운정점",
    account: {
      id: "seoyeon@naver.com",
      role: "admin",
    },
    membership: {
      type: "체험회원",
      level: "VIP",
      registeredAt: "2024-06-30",
      lastReRegisteredAt: "2024-06-30",
      expirationDate: "2024-07-30",
    },
    stats: {
      height: 169,
      currentWeight: 64,
      goalWeight: 56,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "안 준혁",
    contact: {
      phone: "010-4567-8901",
      email: "junhyuk@gmail.com",
    },
    birthdate: "1986-11-09",
    gender: "남성",
    location: "파주 운정점",
    account: {
      id: "junhyuk@gmail.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "VIP",
      registeredAt: "2023-10-15",
      lastReRegisteredAt: "2024-10-15",
      expirationDate: "2025-10-15",
    },
    stats: {
      height: 182,
      currentWeight: 87,
      goalWeight: 80,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "오 지민",
    contact: {
      phone: "010-5678-9012",
      email: "jimin@daum.net",
    },
    birthdate: "1994-03-26",
    gender: "여성",
    location: "파주 운정점",
    account: {
      id: "jimin@daum.net",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "VIP",
      registeredAt: "2024-03-05",
      lastReRegisteredAt: "2024-03-05",
      expirationDate: "2025-03-05",
    },
    stats: {
      height: 166,
      currentWeight: 61,
      goalWeight: 54,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "신 동현",
    contact: {
      phone: "010-6789-0123",
      email: "donghyun@naver.com",
    },
    birthdate: "1980-12-01",
    gender: "남성",
    location: "파주 운정점",
    account: {
      id: "donghyun@naver.com",
      role: "admin",
    },
    membership: {
      type: "종료",
      level: "VIP",
      registeredAt: "2021-11-10",
      lastReRegisteredAt: "2022-11-10",
      expirationDate: "2023-11-10",
    },
    stats: {
      height: 174,
      currentWeight: 79,
      goalWeight: 72,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "이 수빈",
    contact: {
      phone: "010-7890-1234",
      email: "subin@gmail.com",
    },
    birthdate: "1998-05-17",
    gender: "여성",
    location: "파주 운정점",
    account: {
      id: "subin@gmail.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "VIP",
      registeredAt: "2023-06-20",
      lastReRegisteredAt: "2024-06-20",
      expirationDate: "2025-06-20",
    },
    stats: {
      height: 162,
      currentWeight: 57,
      goalWeight: 50,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "김 재원",
    contact: {
      phone: "010-8901-2345",
      email: "jaewon@kakao.com",
    },
    birthdate: "1985-08-14",
    gender: "남성",
    location: "파주 운정점",
    account: {
      id: "jaewon@kakao.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "VIP",
      registeredAt: "2022-04-05",
      lastReRegisteredAt: "2024-04-05",
      expirationDate: "2025-04-05",
    },
    stats: {
      height: 178,
      currentWeight: 83,
      goalWeight: 75,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "박 하린",
    contact: {
      phone: "010-9012-3456",
      email: "harin@naver.com",
    },
    birthdate: "1996-10-08",
    gender: "여성",
    location: "파주 운정점",
    account: {
      id: "harin@naver.com",
      role: "admin",
    },
    membership: {
      type: "체험회원",
      level: "VIP",
      registeredAt: "2024-06-15",
      lastReRegisteredAt: "2024-06-15",
      expirationDate: "2024-07-15",
    },
    stats: {
      height: 164,
      currentWeight: 59,
      goalWeight: 52,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
  {
    name: "최 민석",
    contact: {
      phone: "010-0123-4567",
      email: "minseok@gmail.com",
    },
    birthdate: "1981-06-23",
    gender: "남성",
    location: "파주 운정점",
    account: {
      id: "minseok@gmail.com",
      role: "admin",
    },
    membership: {
      type: "등록회원",
      level: "VIP",
      registeredAt: "2023-07-10",
      lastReRegisteredAt: "2024-07-10",
      expirationDate: "2025-07-10",
    },
    stats: {
      height: 175,
      currentWeight: 80,
      goalWeight: 73,
      exerciseGoal: "",
      averageExerciseTime: "",
      sleepQuality: "",
      particulars: "",
      menstrualCycle: {
        averageCycleWeeks: 0,
        currentFlowStandard: "",
        premenstrualSymptoms: "",
        activityRestrictionDuringPeriod: false,
      },
    },
    job: "",
    attendance: {
      monthlyCount: 0,
      totalCount: 0,
    },
  },
];
