import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
// import StyledComponentsRegistry from "../components/StyledComponentsRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Noto_Sans({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        {/* <StyledComponentsRegistry> */}
        {children}
        {/* </StyledComponentsRegistry> */}
      </body>
    </html>
  );
}
